//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLizard.Policy {
    
    
    public partial struct Base : CityLizard.Policy.INumeric<System.Byte>, CityLizard.Policy.INumeric<System.SByte>, CityLizard.Policy.INumeric<System.UInt16>, CityLizard.Policy.INumeric<System.Int16>, CityLizard.Policy.INumeric<System.UInt32>, CityLizard.Policy.INumeric<System.Int32>, CityLizard.Policy.INumeric<System.UInt64>, CityLizard.Policy.INumeric<System.Int64>, CityLizard.Policy.INumeric<System.Decimal>, CityLizard.Policy.INumeric<System.Single>, CityLizard.Policy.INumeric<System.Double> {
        
        byte CityLizard.Policy.INumeric<System.Byte>.Zero() {
            return 0;
        }
        
        byte CityLizard.Policy.INumeric<System.Byte>.Add(byte a, byte b) {
            return ((byte)((a + b)));
        }
        
        sbyte CityLizard.Policy.INumeric<System.SByte>.Zero() {
            return 0;
        }
        
        sbyte CityLizard.Policy.INumeric<System.SByte>.Add(sbyte a, sbyte b) {
            return ((sbyte)((a + b)));
        }
        
        ushort CityLizard.Policy.INumeric<System.UInt16>.Zero() {
            return 0;
        }
        
        ushort CityLizard.Policy.INumeric<System.UInt16>.Add(ushort a, ushort b) {
            return ((ushort)((a + b)));
        }
        
        short CityLizard.Policy.INumeric<System.Int16>.Zero() {
            return 0;
        }
        
        short CityLizard.Policy.INumeric<System.Int16>.Add(short a, short b) {
            return ((short)((a + b)));
        }
        
        uint CityLizard.Policy.INumeric<System.UInt32>.Zero() {
            return 0;
        }
        
        uint CityLizard.Policy.INumeric<System.UInt32>.Add(uint a, uint b) {
            return ((uint)((a + b)));
        }
        
        int CityLizard.Policy.INumeric<System.Int32>.Zero() {
            return 0;
        }
        
        int CityLizard.Policy.INumeric<System.Int32>.Add(int a, int b) {
            return ((int)((a + b)));
        }
        
        ulong CityLizard.Policy.INumeric<System.UInt64>.Zero() {
            return 0;
        }
        
        ulong CityLizard.Policy.INumeric<System.UInt64>.Add(ulong a, ulong b) {
            return ((ulong)((a + b)));
        }
        
        long CityLizard.Policy.INumeric<System.Int64>.Zero() {
            return 0;
        }
        
        long CityLizard.Policy.INumeric<System.Int64>.Add(long a, long b) {
            return ((long)((a + b)));
        }
        
        decimal CityLizard.Policy.INumeric<System.Decimal>.Zero() {
            return 0;
        }
        
        decimal CityLizard.Policy.INumeric<System.Decimal>.Add(decimal a, decimal b) {
            return ((decimal)((a + b)));
        }
        
        float CityLizard.Policy.INumeric<System.Single>.Zero() {
            return 0;
        }
        
        float CityLizard.Policy.INumeric<System.Single>.Add(float a, float b) {
            return ((float)((a + b)));
        }
        
        double CityLizard.Policy.INumeric<System.Double>.Zero() {
            return 0;
        }
        
        double CityLizard.Policy.INumeric<System.Double>.Add(double a, double b) {
            return ((double)((a + b)));
        }
    }
}
