//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("0.0.0.82")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.0.0.82")]
[assembly: System.Reflection.AssemblyTitleAttribute("CityLizard.CodeDom")]
[assembly: System.Reflection.AssemblyCompanyAttribute("CityLizard")]
[assembly: System.Reflection.AssemblyProductAttribute("CityLizard.CodeDom")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © CityLizard 2010")]

